# Generated by Django 2.0.6 on 2018-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.PositiveIntegerField(null=True)),
                ('house', models.PositiveIntegerField(null=True)),
                ('utility', models.PositiveIntegerField(null=True)),
                ('grocery', models.PositiveIntegerField(null=True)),
                ('transport', models.PositiveIntegerField(null=True)),
                ('health', models.PositiveIntegerField(null=True)),
                ('entertainment', models.PositiveIntegerField(null=True)),
                ('debt', models.PositiveIntegerField(null=True)),
                ('others', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('pnum', models.PositiveIntegerField()),
                ('addrs', models.CharField(max_length=100)),
                ('amt', models.PositiveIntegerField()),
            ],
        ),
    ]
