# Generated by Django 2.0.6 on 2018-06-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='date',
        ),
    ]
